# Generated by Django 4.0.5 on 2022-07-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autos', '0004_autos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='autos'),
        ),
    ]
