# Generated by Django 4.0.5 on 2022-07-05 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autos', '0005_alter_autos_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camionetas',
        ),
        migrations.DeleteModel(
            name='Motocicletas',
        ),
    ]
